# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
# Project Configuration
project.name=Hikage
project.description=The IntelliJ Platform and Android Studio plugin for Hikage.
project.url=https://github.com/BetterAndroid/hikage-intellij-plugin
project.groupName=com.highcapable.hikage
project.pluginId=${project.groupName}.intellij
project.version="1.0.0"
project.reference.hikage-core.moduleName=hikage-core
project.intellij-platform.bundled-plugin-kotlin=org.jetbrains.kotlin
project.intellij-platform.bundled-plugin-android=org.jetbrains.android
project.intellij-platform.android-studio.version="2026.1.1.10"
project.intellij-platform.idea.version="261"