# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
# Project Configuration
project.name=HikageIntelliJPlugin
project.description=The IntelliJ Platform and Android Studio plugin for Hikage.
project.url=https://github.com/BetterAndroid/Hikage-IntelliJ-Plugin
project.groupName=com.highcapable.hikage
project.version="1.0.0"
project.hikage-intellij-plugin.namespace=${project.groupName}.intellij
project.hikage-intellij-plugin.moduleName=hikage-intellij-plugin
project.hikage-intellij-plugin.pluginId=${project.groupName}.intellij
project.hikage-intellij-plugin.implementationClass="${project.hikage-intellij-plugin.namespace}.HikageIntelliJPlugin"
