# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
# Project Configuration
project.name=Hikage
project.description=The IntelliJ Platform and Android Studio plugin for Hikage.
project.url=https://github.com/BetterAndroid/hikage-intellij-plugin
project.vendor.name=HighCapable
project.vendor.email=qzmmcn@163.com
project.vendor.url=https://github.com/BetterAndroid/Hikage
project.groupName=com.highcapable.hikage
project.pluginId=${project.groupName}
project.version="1.0.0"
project.android-lint-mirror.kotlin.sourceDir=src/android-lint-mirror/kotlin
project.android-lint-mirror.resourcesDir=src/android-lint-mirror/resources
project.bundled-dictionary.name=hikage.dic
project.testing.intellijPlatformTesting.system-property.test-data.key=hikage.integration.test.data
project.testing.intellijPlatformTesting.system-property.root-project.key=hikage.integration.root.project
project.testing.intellijPlatformTesting.system-property.ide-path.key=hikage.integration.ide.path
project.testing.intellijPlatformTesting.test-data.path=src/integrationTest/testData
project.reference.hikage-bom.moduleName=hikage-bom
# TODO: Change to release version when the plugin is released.
project.reference.hikage-bom.version="1.1.1-dev"
project.reference.hikage-core.moduleName=hikage-core
project.reference.hikage-extension.moduleName=hikage-extension
project.reference.hikage-extension-betterandroid.moduleName=hikage-extension-betterandroid
project.reference.hikage-runtime-attribute.moduleName=hikage-runtime-attribute
project.reference.hikage-widget-foundation.moduleName=hikage-widget-foundation
project.reference.hikage-widget-androidx.moduleName=hikage-widget-androidx
project.reference.hikage-widget-material.moduleName=hikage-widget-material
project.reference.hikage-gradle-plugin.moduleName=hikage-gradle-plugin
# TODO: Change to release version when the plugin is released.
project.reference.hikage-gradle-plugin.version="1.0.1-dev"
project.reference.betterandroid.groupName=com.highcapable.betterandroid
project.reference.betterandroid.ui-component-adapter.moduleName=ui-component-adapter
project.intellij-platform.bundled-plugin-kotlin=org.jetbrains.kotlin
project.intellij-platform.bundled-plugin-android=org.jetbrains.android
project.intellij-platform.bundled-plugin-gradle=com.intellij.gradle
project.intellij-platform.android-studio.version="2026.1.2.10"
project.intellij-platform.idea.version="261"
project.settings.service.className=com.highcapable.hikage.settings.SettingsService