[versions]
kotlin = "2.4.0"
kavaref-bom = "1.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform" }

[libraries]
kavaref-bom = { module = "com.highcapable.kavaref:kavaref-bom", version.ref = "kavaref-bom" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core" }
kavaref-jvm = { module = "com.highcapable.kavaref:kavaref-jvm" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension" }