/*
 * Hikage - A real-time Android View runtime powered by Kotlin DSL.
 * Copyright (C) 2019 HighCapable
 * https://github.com/BetterAndroid/Hikage
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2026/7/15.
 */
package com.highcapable.hikage.intellij.dsl.rename

import com.highcapable.hikage.intellij.project.ProjectGate
import com.intellij.codeInsight.hint.HintManager
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.actionSystem.DataContext
import com.intellij.openapi.editor.Editor
import com.intellij.openapi.project.Project
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.refactoring.rename.PsiElementRenameHandler
import com.intellij.refactoring.rename.RenameHandler
import com.intellij.refactoring.util.CommonRefactoringUtil

/**
 * Intercepts Kotlin's rename dispatcher before it routes Hikage dynamic performers to the built-in synthetic-stub handler.
 */
class HikageViewRenameHandler : RenameHandler {

    private companion object {
        const val PERFORMER_RENAME_UNAVAILABLE_MESSAGE =
            "Only performers generated by an unaliased <code>@HikageView</code> class in the current project can be renamed."
        const val PERFORMER_IMPORT_RENAME_UNAVAILABLE_MESSAGE =
            "Hikage performer imports cannot be renamed."
    }

    override fun isAvailableOnDataContext(dataContext: DataContext): Boolean {
        val caretElement = HikageViewRenameSupport.findCaretElement(dataContext)
        val element = PsiElementRenameHandler.getElement(dataContext) ?: caretElement ?: return false
        if (!ProjectGate.from(element.project).isEnabled()) return false
        val view = HikageViewRenameSupport.findProjectHikageView(element)
        val performer = HikageViewRenameSupport.findGeneratedPerformer(element)
        val protectedImport = HikageViewRenameSupport.findHikageWidgetImport(caretElement)
            ?: HikageViewRenameSupport.findHikageWidgetImport(element)

        return view != null || performer != null || protectedImport != null
    }

    override fun invoke(project: Project, editor: Editor, file: PsiFile, dataContext: DataContext) {
        val caretElement = file.findElementAt(editor.caretModel.offset)
        if (HikageViewRenameSupport.findHikageWidgetImport(caretElement) != null) {
            HintManager.getInstance().showErrorHint(editor, PERFORMER_IMPORT_RENAME_UNAVAILABLE_MESSAGE)
            return
        }

        val element = PsiElementRenameHandler.getElement(dataContext)
            ?: CommonRefactoringUtil.getElementAtCaret(editor, file)
        invokeRename(project, editor, element)
    }

    override fun invoke(project: Project, elements: Array<out PsiElement>, dataContext: DataContext) {
        val editor = CommonDataKeys.EDITOR.getData(dataContext)
        if (HikageViewRenameSupport.findHikageWidgetImport(HikageViewRenameSupport.findCaretElement(dataContext)) != null) {
            editor?.let { HintManager.getInstance().showErrorHint(it, PERFORMER_IMPORT_RENAME_UNAVAILABLE_MESSAGE) }
            return
        }

        val element = elements.singleOrNull() ?: PsiElementRenameHandler.getElement(dataContext) ?: return
        invokeRename(project, editor, element)
    }

    private fun invokeRename(project: Project, editor: Editor?, element: PsiElement) {
        if (HikageViewRenameSupport.findHikageWidgetImport(element) != null) {
            editor?.let { HintManager.getInstance().showErrorHint(it, PERFORMER_IMPORT_RENAME_UNAVAILABLE_MESSAGE) }
            return
        }

        val performer = HikageViewRenameSupport.findGeneratedPerformer(element)
        val renamablePerformer = HikageViewRenameSupport.findRenamablePerformer(element)
        if (performer != null && renamablePerformer == null) {
            editor?.let { HintManager.getInstance().showErrorHint(it, PERFORMER_RENAME_UNAVAILABLE_MESSAGE) }
            return
        }

        PsiElementRenameHandler.rename(element, project, element, editor, null, HikageViewRenameProcessor())
    }
}
